### PR TITLE
Update project files + README

### PR DESCRIPTION
**Pull request by ehayman**
* Updated README text to remove ambiguity around requirements for front-end tools
* Removed gulpfile + associated assets to remove the assumption that jQuery + .scss compilation with gulp is required

### CODE REVIEW

**Comment by dustincoates** [comment]
@ehayman This looks great. Since changes are being made, what are your thoughts on our discussion of adding something to the scoring rubric that refers to intra-team communication skills?

**Comment by ehayman** [comment]
@dustincoates I'm wondering if "Ask for clarification when necessary?" should almost move outside the "Customer Questions" section to be more generic?

**Comment by dustincoates** [comment]
@ehayman Sounds good to me. 👍

**Comment by ehayman** [comment]
OK and now I went to move it and I'm not sure how best to squeeze it in "Overall Impressions" which is based off the "top 10%" prompt, and it feels like an item under "Communication skills". 🤦‍♀️

**Comment by dustincoates** [comment]
@ehayman I think it could fit in "technical assignment."

**Comment by ehayman** [comment]
Works for me, updated.

**Pull request merged**
